# ⚠️ DEPRECATED ⚠️
# This Docker Compose setup is no longer actively maintained.
# Please use the npm-based wp-env workflow instead.
#
# See ../bricks-etch-migration/README.md for setup instructions.
#
# This file is retained for reference only.
#
# For new development, use:
#   cd ../bricks-etch-migration
#   npm run dev
#
version: '3.8'

services:
  bricks-db:
    image: mysql:8.0
    container_name: b2e-bricks-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bricks_wp
      MYSQL_USER: bricks_user
      MYSQL_PASSWORD: bricks_pass
    volumes:
      - bricks-db-data:/var/lib/mysql
    networks:
      - b2e-network

  etch-db:
    image: mysql:8.0
    container_name: b2e-etch-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: etch_wp
      MYSQL_USER: etch_user
      MYSQL_PASSWORD: etch_pass
    volumes:
      - etch-db-data:/var/lib/mysql
    networks:
      - b2e-network

  bricks-wp:
    image: wordpress:latest
    container_name: b2e-bricks-wp
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: bricks-db
      WORDPRESS_DB_NAME: bricks_wp
      WORDPRESS_DB_USER: bricks_user
      WORDPRESS_DB_PASSWORD: bricks_pass
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    volumes:
      - bricks-wp-data:/var/www/html
      - ../bricks-etch-migration:/var/www/html/wp-content/plugins/bricks-etch-migration
    depends_on:
      - bricks-db
    networks:
      - b2e-network

  etch-wp:
    image: wordpress:latest
    container_name: b2e-etch-wp
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: etch-db
      WORDPRESS_DB_NAME: etch_wp
      WORDPRESS_DB_USER: etch_user
      WORDPRESS_DB_PASSWORD: etch_pass
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    volumes:
      - etch-wp-data:/var/www/html
      - ../bricks-etch-migration:/var/www/html/wp-content/plugins/bricks-etch-migration
    depends_on:
      - etch-db
    networks:
      - b2e-network

  wpcli:
    image: wordpress:cli
    container_name: b2e-wpcli
    command: tail -f /dev/null
    volumes:
      - bricks-wp-data:/var/www/html/bricks
      - etch-wp-data:/var/www/html/etch
      - ../bricks-etch-migration:/var/www/html/bricks/wp-content/plugins/bricks-etch-migration
      - ../bricks-etch-migration:/var/www/html/etch/wp-content/plugins/bricks-etch-migration
      - ./scripts:/scripts:ro
    depends_on:
      - bricks-wp
      - etch-wp
    networks:
      - b2e-network

volumes:
  bricks-db-data:
  etch-db-data:
  bricks-wp-data:
  etch-wp-data:

networks:
  b2e-network:
    driver: bridge
