version: '3.8'

services:
  # WordPress mit Bricks (Source Site)
  wordpress-bricks:
    image: wordpress:6.4-apache
    container_name: b2e-bricks
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql-bricks
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_bricks
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    volumes:
      - ./wordpress-bricks:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ../bricks-etch-migration:/var/www/html/wp-content/plugins/bricks-etch-migration
    depends_on:
      - mysql-bricks
    networks:
      - b2e-network

  # WordPress mit Etch (Target Site)
  wordpress-etch:
    image: wordpress:6.4-apache
    container_name: b2e-etch
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: mysql-etch
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_etch
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    volumes:
      - ./wordpress-etch:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ../bricks-etch-migration:/var/www/html/wp-content/plugins/bricks-etch-migration
    depends_on:
      - mysql-etch
    networks:
      - b2e-network

  # MySQL für Bricks Site
  mysql-bricks:
    image: mysql:8.0
    container_name: b2e-mysql-bricks
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_bricks
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql-bricks-data:/var/lib/mysql
    networks:
      - b2e-network

  # MySQL für Etch Site
  mysql-etch:
    image: mysql:8.0
    container_name: b2e-mysql-etch
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_etch
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql-etch-data:/var/lib/mysql
    networks:
      - b2e-network

  # phpMyAdmin für Datenbank-Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: b2e-phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql-bricks,mysql-etch
    depends_on:
      - mysql-bricks
      - mysql-etch
    networks:
      - b2e-network

volumes:
  mysql-bricks-data:
  mysql-etch-data:

networks:
  b2e-network:
    driver: bridge
