name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f
        with:
          php-version: '8.1'
          coverage: none
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --no-scripts
        working-directory: etch-fusion-suite

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=phpcs.xml.dist
        working-directory: etch-fusion-suite

  test:
    name: PHPUnit (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.1', '8.2', '8.3', '8.4']
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
      WP_CORE_DIR: /tmp/wordpress
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: mysqli

      - name: Install Subversion
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
        working-directory: etch-fusion-suite

      - name: Create WordPress test database
        run: mysql -h 127.0.0.1 -uroot -e 'CREATE DATABASE IF NOT EXISTS wordpress_test;'

      - name: Install WordPress test suite
        run: bash etch-fusion-suite/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest

      - name: Run PHPUnit suite
        run: vendor/bin/phpunit -c etch-fusion-suite/phpunit.xml.dist
        working-directory: etch-fusion-suite

  node:
    name: Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0

      - name: Prepare Node modules directory
        run: mkdir -p etch-fusion-suite/node_modules

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: etch-fusion-suite/package-lock.json

      - name: Install Node dependencies
        run: npm ci
        working-directory: etch-fusion-suite
