name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up PHP
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f
        with:
          php-version: "8.1"
          coverage: none
          tools: composer

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Validate plugin headers
        run: |
          chmod +x scripts/validate-plugin-headers.sh
          scripts/validate-plugin-headers.sh
        working-directory: bricks-etch-migration
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Install production dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress
        working-directory: bricks-etch-migration

      - name: Create plugin ZIP
        run: |
          cd bricks-etch-migration
          zip -r ../bricks-etch-migration.zip . \
            -x "*.git*" \
            -x "*node_modules/*" \
            -x "*.wp-env*" \
            -x "*package*.json" \
            -x "*composer.json" \
            -x "*composer.lock" \
            -x "*phpcs.xml.dist" \
            -x "*phpunit.xml.dist" \
            -x "*.DS_Store" \
            -x "*tests/*" \
            -x "*scripts/*"

      - name: Extract changelog
        id: changelog
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          CHANGELOG=$(awk "/## \[${VERSION}\]/{flag=1; next} /## \[/{flag=0} flag" CHANGELOG.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          files: bricks-etch-migration.zip
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
